version: '3.5'

services:
  server:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/linguagens?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MARIADB_DATABASE: linguagens
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: