version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/linguagens
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'linguagens'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: