version: '3.7'
services:
  server:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  db:
    image: "mariadb:10.5.8"
    restart: always
    environment:
      MYSQL_DATABASE: linguagens
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: